### ISSUE TITLE
Check Team Project 2 Submission

### ISSUE THREAD

**Issue by YonaMilstein** [YonaMilstein/QUALITA#2]
## Project progress:

- [x] Open project repository

- [x] Creating and editing relevant README

- [x] Creating USER MANUAL for further information on the project

- [x] Creating TEAM PAGE for further information on the team

- [x] Inception/planning the project

- [x] Creating the PRODUCT PAGE

- [ ] Meeting with the client

**Comment by robi-y** [comment]
Excellent work, some comments:
- Project description is missing (edit via repository settings)
- Readme: it seems the vision is of the organization, not your project, remove or comment out badges that still point to jce-il/template-project
- Inception: risks are very general not project specific, - A use case diagram in not optimal for discussing software structure, better use deployment or even class diagrams

Please grant me access to this repository so I could change issue status,
